### ISSUE TITLE
Broken link on README

### ISSUE THREAD

**Issue by xarxziux** [exercism/r#103]
On the README, under the section [Porting exercises](https://github.com/exercism/r#porting-exercises), the text [list of missing exercises](http://exercism.io/languages/r/todo) is linked to http://exercism.io/languages/r/todo, but this re-directs to https://exercism.io/contribute.  The README needs to be updated to either fix the link, or remove the line if this feature no longer exists.

I've not been able to find any link for missing exercises so I'm assuming that the latter is the case.  Can you please confirm this?

**Comment by katrinleinweber** [comment]
Good catch :-) I believe that the [general porting guide](https://github.com/exercism/docs/blob/798d812dc886a0b6951004cffa072ea649b2b289/you-can-help/implement-an-exercise-from-specification.md#L33) (@kytrinyx?) needs to be updated to align with the new site, so I'd wait for that.

**Comment by katrinleinweber** [comment]
Also, the `porting an exercise`-link can be updated to https://github.com/exercism/docs/blob/master/you-can-help/implement-an-exercise-from-specification.md

**Comment by kytrinyx** [comment]
I have a mountain of work to do in the docs to get everything cleared up. It's going to take a while, I'm afraid.

**Comment by xarxziux** [comment]
Closing this, as the page has been updated.
