### ISSUE TITLE
Version of R running on Exercism

### ISSUE THREAD

**Issue by vgherard** [exercism/r#186]
Under what version of R are the tests of exercises being ran on Exercism? I searched a bit and did not find it mentioned.

It might be useful to specify the version, especially since `R 4.1` introduces new features (e.g. the `|>` native pipe) which were not available in older versions. 

PS: *enhorabuena* for the new user interface, looks great!

**Comment by jonmcalder** [comment]
Thanks for the question and for raising this!

Currently the tests are running against R v3.6.3, but I agree that it should probably move to R v4.1.1 - I'll look into that. Hopefully it can simply be updated without changes needed elsewhere.

Currently I think the only way to see the version the test runner is using is to check directly [here](https://github.com/exercism/r-test-runner/blob/main/Dockerfile)

We could probably document the R version used for tests in the [testing docs](https://exercism.org/docs/tracks/r/tests) on the website, but I don't see any other tracks doing so which makes me wonder whether it's either not considered important enough to mention or it's covered elsewhere on the platform (putting it in the docs means they'll have to be kept in sync with the test runners which shouldn't have to be done manually cos it'll inevitably be overlooked at some point). In most cases the specific language version used shouldn't matter (other than with major language versions like the addition of the native pipe in R version 4 which you've raised here), but I agree it would be helpful to know the specific version in rare cases where one may run into version specific behaviour.

I'll raise it with other track maintainers to see if there's something I'm missing.

**Comment by jonmcalder** [comment]
Oh and gracias regarding the new interface. Can't take any credit personally (that's all down to the core Exercism team), but glad you like it!

**Comment by jonmcalder** [comment]
Update: the language version being used for testing will be reflected in the editor and the UI in a future update to the Exercism platform.

Am going to leave this issue open until I've updated the test runner to use R v4.

**Comment by vgherard** [comment]
> Update: the language version being used for testing will be reflected in the editor and the UI in a future update to the Exercism platform.
> 
> Am going to leave this issue open until I've updated the test runner to use R v4.

I was precisely going to ask whether it could be an idea to explicitate the version in the editor :-) I have seen this done in other places. I was also asking about the version because the other day I was commenting to a student that his/her solution did not pass the test suite, which I realize was likely due to me testing locally with R 4.1.

**Comment by jonmcalder** [comment]
> I was also asking about the version because the other day I was commenting to a student that his/her solution did not pass the test suite, which I realize was likely due to me testing locally with R 4.1. 

Can you recall (or could you check) why his / her solution did not pass the test suite and if it really was due to you testing locally with R 4.1?

I think the single thing that is most likely to cause test failures in certain exercises will be the change to the stringsAsFactors default in R > 4, but it'd be good to know what else to look out for when updating the test runner.

**Comment by vgherard** [comment]
> > I was also asking about the version because the other day I was commenting to a student that his/her solution did not pass the test suite, which I realize was likely due to me testing locally with R 4.1.
> 
> Can you recall (or could you check) why his / her solution did not pass the test suite and if it really was due to you testing locally with R 4.1?
> 
> I think the single thing that is most likely to cause test failures in certain exercises will be the change to the stringsAsFactors default in R > 4, but it'd be good to know what else to look out for when updating the test runner.

It was on user "karlzipple" iteration 1 to "perfect number": 
https://exercism.org/mentoring/discussions/4dde5250d1954b94a16639c7bc95a61e

I just re-checked on it and I was a bit sloppy, the test suite gets actually passed, however with an unexpected warning in the test `"Negative integer is rejected (not a natural number)"` (due to the call to `sqrt(-1)`) - I would consider this result a failure, but that's matter of opinion. What's sure is that this is not due to `R < 4`, so that sorry for confusing things up.

**Comment by jonmcalder** [comment]
Ok cool. Mentoring discussions are private so I can't look at that, but no problem as you told me what I wanted to know. Thanks for checking on it for me.

Doesn't matter that R < 4 wasn't the issue, I agree that it's worth upgrading the test suite now anyway. At the time that we began working on Exercism v3, the new version of R didn't exist yet, and when the test runner was initially implemented R v4 hadn't been around very long.

**Comment by jonmcalder** [comment]
I've updated the test runner for R to run on v4.1.2 now so that should allow for use of the base R pipe in solutions to exercises (assuming all is working well).

Thanks again for raising this issue and sorry for the long turnaround time!

**Comment by vgherard** [comment]
💯  thank you Jon!

**Comment by glennj** [comment]
I think this relates to exercism/exercism#6096
