### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by iHiD** [exercism/r#344]
@Nerwosolek You have qualified to be a maintainer here. Thank you for your hard work! Would you like to join?

**Comment by Nerwosolek** [comment]
Sure, I can help if you need it!

**Comment by ErikSchierboom** [comment]
Awesome. Thank you!

You should receive an invite to join the org and the team now. You'll also get access to the #maintainers channel on Discord if your Exercism and Discord accounts [are linked](https://exercism.org/settings/integrations).

You can learn more about being a maintainer [here](https://exercism.org/docs/community/maintainers)

Thanks so much for your work, and welcome to the team :)
