### ISSUE TITLE
add (micro)benchmark to test performance

### ISSUE THREAD

**Issue by katrinleinweber** [exercism/r#62]
Several exercise descriptions suggest refactoring a solution for readability, performance etc. I suggest adding a single [`microbenchmark`](https://cran.r-project.org/web/packages/microbenchmark/index.html) to 
- a) either only those exercises, or
- b) each exercise,

in order to provide a quick feedback on the performance. Thoughts, comments, etc.?

Console output for a successful test suite is only few lines, so `microbenchmark`'s results should be visually comparable across runs. I'm not sure how the alternative (automatically benchmark 2 versions of a solution at once) would be possible.

**Comment by jonmcalder** [comment]
This is a cool suggestion. 

Previously I'd wondered whether it might even be possible to include some form of formal benchmark 'testing' for certain exercises where the efficiency of the implementation could or should be part of the focus. I think that is probably tricky territory though, given that runtime is system dependent and thus somewhat variable in nature (I suppose one could build in a buffer but still).

Anyway, I'm guessing that what you're suggesting here is more of a 'soft' inclusion, just to encourage people to look at and consider benchmarking while iterating on solutions? Maybe including commented out benchmarking code or something like that?

**Comment by katrinleinweber** [comment]
I have too little time to work on this further and to ensure compatibility within the existing exercism environment, sorry.

**Comment by jonmcalder** [comment]
No worries! I'm also too busy to look at this at the moment. I may try and revisit it at a later stage though - thanks for the suggestion and the progress made on it so far!
