### ISSUE TITLE
Update track metadata as outlined in #65

### ISSUE THREAD

**Issue by jonmcalder** [exercism/r#66]
- [x] add a rough estimate of difficulty to each exercise (scale: 1-10)
- [x] add topics to each exercise
- [x] choose at most 20 exercises to be core exercises (set core: true, and delete the unlocked_by key)
- [x] for each exercise that is not core, decide which exercise is the prerequisite (max 1)
- [x] leave 3 or 4 simple exercises as (core: false, unlocked_by: null)

**Comment by katrinleinweber** [comment]
Seeing that #69 deals with the topics, I'll start with the difficulty scale and the core.

**Comment by jonmcalder** [comment]
Cool - I think you should start adding these updates as part of #69 too. I figure it's best to do it all in one branch/pull request since all the changes are within one file.

**Comment by katrinleinweber** [comment]
I initially thought the same, but am now a bit concerned that the "Files changed"-tab will become very crowded. Ah, well, let's try it!
