### ISSUE TITLE
grains: total() test is not precise enough

### ISSUE THREAD

**Issue by ttnagata** [exercism/r#84]
The ` total <- function() 2^64-1` function can not be tested properly because the expected output is too large.
All the following functions will pass the test:

```R 
total <- function() 2^64
```
```R 
total <- function() 2^64-1000
```
```R
total <- function()  sum(2^((10:64)-1))
```
I have put some comments on my solution,
 [http://exercism.io/submissions/e1cb23c4e118442da7c46f7ad4593c4e](link),
unfortunately could come up with a way to fix the test.

I found some useful information about R's limitations in this R bloggers [https://www.r-bloggers.com/r-in-a-64-bit-world/](url), but it was not enough to figure how to make a test that could detect these wrong solutions.

I sorry if I cannot be more helpful, feel free to close this issue. I just wanted to let people know about the problem.

**Comment by TheGeoLawton** [comment]
I played around with the R console, and this is definitely an issue.

I thought maybe using format() to remove scientific notation would possibly at least allow comparing the output to a string, but that is not working either. 

Not sure how to resolve the issue either.

**Comment by jonmcalder** [comment]
Thanks @ttnagata for raising this. Completely missed this when I implemented the tests for this exercise. Can't think of any easy or obvious fix at this point - ideally we'd want to avoid a package dependency just to get around R's 32bit integer limitation, which, as that article says is rather behind the times. If we do go that route, then we'd need to include the relevant package dependency as a hint (e.g. see [triangle](https://github.com/exercism/r/blob/master/exercises/triangle/.meta/hints.md)).

Changing the question to reference a smaller board with less squares wouldn't really change the fundamentals of the question, but it seems lame to have to make that kind of concession. 

I'm open to further suggestions here...

**Comment by ttnagata** [comment]
I don't have much experience with these issues, but I think the idea of changing the question to reference a smaller board changes the story behind the exercise (about the chessboard).

On the other hand, I couldn't find a package that fixes the problem. If I had, I would suggest adding a package dependency.
