### ISSUE TITLE
Context required for testthat

### ISSUE THREAD

**Issue by zacchaeusluke** [exercism/r#93]
Using RStudio and `auto_test()` I kept getting `Error in x[[method]](...) : attempt to apply non-function` and it wouldn't do the live reloading properly. I've got the latest version of testthat (2.0.0)

I found [this issue thread](https://github.com/r-lib/testthat/issues/700) which indicates that the test file needs a `context()` line. Adding a `context("Example name")` solved my issues and now the `auto_text()` runs without any error.

**Comment by jonmcalder** [comment]
Thanks for raising this @zacchaeusluke! And thanks also for identifying the solution.

I have checked this locally and verified both the issue and proposed solution. Would you like to contribute a PR to fix this? If not, no worries - just let me know.

**Comment by katrinleinweber** [comment]
Sheffield! :-) Do you know about the RSE groups there: https://rse.shef.ac.uk/blog/soft-carp-at-tuos/ ?

**Comment by zacchaeusluke** [comment]
@jonmcalder No worries, I'll put together a PR

@katrinleinweber nope! I'm just a lowly maths undergrad & haven't really engaged much with local groups
